module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ─── Admin Dark Theme ─────────────────────────────
        "admin-bg":           "#0F1117",
        "admin-bg-secondary":  "#141620",
        "admin-surface":       "#1A1D2E",
        "admin-surface-hover": "#222638",
        "admin-border":        "#2A2D3E",
        "admin-border-hover":  "#3A3D50",
        "admin-text":          "#F9FAFB",
        "admin-text-sub":      "#9CA3AF",
        "admin-text-dim":      "#4B5563",

        // ─── Primary (Amber) ────────────────────────────
        "admin-primary":      "#F59E0B",
        "admin-primary-hover": "#D97706",
        "admin-primary-dim":  "rgba(245,158,11,0.12)",

        // ─── Secondary (Indigo) ──────────────────────────
        "admin-secondary":     "#6366F1",
        "admin-secondary-dim":  "rgba(99,102,241,0.12)",

        // ─── Accent (Purple) ─────────────────────────────
        "admin-accent":        "#8B5CF6",
        "admin-accent-dim":     "rgba(139,92,246,0.12)",

        // ─── Status ──────────────────────────────────────
        "admin-success":      "#10B981",
        "admin-success-dim":  "rgba(16,185,129,0.12)",
        "admin-error":        "#EF4444",
        "admin-error-dim":    "rgba(239,68,68,0.12)",
        "admin-warning":      "#F59E0B",
        "admin-warning-dim":  "rgba(245,158,11,0.12)",
        "admin-info":         "#3B82F6",
        "admin-info-dim":     "rgba(59,130,246,0.12)",

        // ─── Material You Inspired ────────────────────────
        "background":             "#0e0e0f",
        "on-background":          "#ffffff",
        "surface":               "#0e0e0f",
        "surface-dim":            "#0e0e0f",
        "surface-bright":         "#2c2c2d",
        "surface-container-lowest":"#000000",
        "surface-container-low":  "#0F1117",
        "surface-container":      "#141620",
        "surface-container-high": "#1A1D2E",
        "surface-container-highest":"#222638",
        "surface-variant":       "#222638",
        "on-surface":            "#F9FAFB",
        "on-surface-variant":    "#9CA3AF",
        "outline":              "#4B5563",
        "outline-variant":      "#3A3D50",
        "primary":             "#F59E0B",
        "primary-dim":         "#D97706",
        "primary-fixed":       "#F59E0B",
        "primary-fixed-dim":   "#D97706",
        "primary-container":    "#F59E0B",
        "on-primary":          "#000000",
        "on-primary-container": "#000000",
        "on-primary-fixed":    "#000000",
        "on-primary-fixed-variant": "#000000",
        "inverse-primary":     "#D97706",
        "secondary":           "#6366F1",
        "secondary-dim":       "#4F46E5",
        "secondary-container":  "#6366F1",
        "on-secondary":        "#FFFFFF",
        "on-secondary-container":"#FFFFFF",
        "tertiary":           "#8B5CF6",
        "tertiary-dim":       "#7C3AED",
        "tertiary-container":  "#8B5CF6",
        "on-tertiary":        "#FFFFFF",
        "on-tertiary-container":"#FFFFFF",
        "error":              "#EF4444",
        "error-dim":          "#DC2626",
        "error-container":     "#EF4444",
        "on-error":           "#FFFFFF",
        "on-error-container":  "#FFFFFF",
        "inverse-surface":    "#F9FAFB",
        "inverse-on-surface":  "#1A1D2E",
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', "sans-serif"],
        body:     ["'Plus Jakarta Sans'", "sans-serif"],
        label:    ["'Plus Jakarta Sans'", "sans-serif"],
      },
      borderRadius: {
        "admin-sm": "8px",
        "admin-md": "12px",
        "admin-lg": "18px",
        "admin-xl": "24px",
      },
    },
  },
};
