module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background":                "#0e0e0f",
        "on-background":             "#ffffff",
        "surface":                   "#0e0e0f",
        "surface-dim":               "#0e0e0f",
        "surface-bright":            "#2c2c2d",
        "surface-container-lowest":  "#000000",
        "surface-container-low":     "#131314",
        "surface-container":         "#1a191b",
        "surface-container-high":    "#201f21",
        "surface-container-highest": "#262627",
        "surface-variant":           "#262627",
        "on-surface":                "#ffffff",
        "on-surface-variant":        "#adaaab",
        "outline":                   "#767576",
        "outline-variant":           "#484849",
        "primary":                   "#84adff",
        "primary-dim":               "#0070ea",
        "primary-fixed":             "#6c9fff",
        "primary-fixed-dim":         "#5091ff",
        "primary-container":         "#6c9fff",
        "on-primary":                "#002d64",
        "on-primary-container":      "#00214e",
        "on-primary-fixed":          "#000000",
        "on-primary-fixed-variant":  "#002a60",
        "inverse-primary":           "#005bc1",
        "secondary":                 "#7e98ff",
        "secondary-dim":             "#7e98ff",
        "secondary-container":       "#1e3da1",
        "secondary-fixed":           "#c6cfff",
        "secondary-fixed-dim":       "#b3c1ff",
        "on-secondary":              "#00185d",
        "on-secondary-container":    "#c4ceff",
        "on-secondary-fixed":        "#00298b",
        "on-secondary-fixed-variant":"#2b48ac",
        "tertiary":                  "#fab0ff",
        "tertiary-dim":              "#e48fed",
        "tertiary-fixed":            "#f39cfb",
        "tertiary-fixed-dim":        "#e48fed",
        "tertiary-container":        "#f39cfb",
        "on-tertiary":               "#6a1f77",
        "on-tertiary-container":     "#60136d",
        "on-tertiary-fixed":         "#41004d",
        "on-tertiary-fixed-variant": "#6a1f77",
        "error":                     "#ff716c",
        "error-dim":                 "#d7383b",
        "error-container":           "#9f0519",
        "on-error":                  "#490006",
        "on-error-container":        "#ffa8a3",
        "inverse-surface":           "#fcf8f9",
        "inverse-on-surface":        "#565556",
        "surface-tint":              "#84adff",
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
      },
    },
  },
};