export const ACHIEVEMENTS_DEF = {
    FIRST_SURVEY: {
        code: "FIRST_SURVEY",
        name: "Người mới",
        description: "Tạo khảo sát đầu tiên",
        icon: "🌱",
        category: "SURVEY_CREATION",
        star_reward: 20,
        tier: "BRONZE",
        condition_type: "SURVEY_COUNT",
        condition_value: 1,
    },
    FIVE_SURVEYS: {
        code: "FIVE_SURVEYS",
        name: "Khảo sát viên",
        description: "Tạo 5 khảo sát",
        icon: "📝",
        category: "SURVEY_CREATION",
        star_reward: 50,
        tier: "SILVER",
        condition_type: "SURVEY_COUNT",
        condition_value: 5,
    },
    TEN_SURVEYS: {
        code: "TEN_SURVEYS",
        name: "Chuyên gia khảo sát",
        description: "Tạo 10 khảo sát",
        icon: "🏆",
        category: "SURVEY_CREATION",
        star_reward: 100,
        tier: "GOLD",
        condition_type: "SURVEY_COUNT",
        condition_value: 10,
    },
    FIFTY_SURVEYS: {
        code: "FIFTY_SURVEYS",
        name: "Bậc thầy khảo sát",
        description: "Tạo 50 khảo sát",
        icon: "👑",
        category: "SURVEY_CREATION",
        star_reward: 250,
        tier: "PLATINUM",
        condition_type: "SURVEY_COUNT",
        condition_value: 50,
    },
    HUNDRED_SURVEYS: {
        code: "HUNDRED_SURVEYS",
        name: "Huyền thoại khảo sát",
        description: "Tạo 100 khảo sát",
        icon: "💎",
        category: "SURVEY_CREATION",
        star_reward: 500,
        tier: "DIAMOND",
        condition_type: "SURVEY_COUNT",
        condition_value: 100,
    },

    // PARTICIPATION
    FIRST_RESPONSE: {
        code: "FIRST_RESPONSE",
        name: "Người tham gia",
        description: "Hoàn thành khảo sát đầu tiên",
        icon: "🎯",
        category: "PARTICIPATION",
        star_reward: 20,
        tier: "BRONZE",
        condition_type: "RESPONSE_COUNT",
        condition_value: 1,
    },
    TEN_RESPONSES: {
        code: "TEN_RESPONSES",
        name: "Khách quen",
        description: "Hoàn thành 10 khảo sát",
        icon: "🙋",
        category: "PARTICIPATION",
        star_reward: 50,
        tier: "SILVER",
        condition_type: "RESPONSE_COUNT",
        condition_value: 10,
    },
    FIFTY_RESPONSES: {
        code: "FIFTY_RESPONSES",
        name: "Người tích cực",
        description: "Hoàn thành 50 khảo sát",
        icon: "🚀",
        category: "PARTICIPATION",
        star_reward: 150,
        tier: "GOLD",
        condition_type: "RESPONSE_COUNT",
        condition_value: 50,
    },
    HUNDRED_RESPONSES: {
        code: "HUNDRED_RESPONSES",
        name: "Siêu sao khảo sát",
        description: "Hoàn thành 100 khảo sát",
        icon: "⭐",
        category: "PARTICIPATION",
        star_reward: 300,
        tier: "PLATINUM",
        condition_type: "RESPONSE_COUNT",
        condition_value: 100,
    },

    // SOCIAL - Người tham gia đầu tiên
    FIRST_RESPONDER_ACH: {
        code: "FIRST_RESPONDER",
        name: "Người đi đầu",
        description: "Là người đầu tiên hoàn thành một khảo sát",
        icon: "🏃",
        category: "SOCIAL",
        star_reward: 30,
        tier: "BRONZE",
        condition_type: "FIRST_RESPONSE_ACH",
        condition_value: 1,
    },

    // SURVEY với 100 người tham gia
    VIRAL_SURVEY: {
        code: "VIRAL_SURVEY",
        name: "Khảo sát viral",
        description: "Có 100 người tham gia khảo sát của bạn",
        icon: "🦠",
        category: "SOCIAL",
        star_reward: 200,
        tier: "GOLD",
        condition_type: "SURVEY_RESPONSES",
        condition_value: 100,
    },

    // STREAK achievements
    STREAK_3: {
        code: "STREAK_3",
        name: "Kiên trì",
        description: "Điểm danh 3 ngày liên tiếp",
        icon: "🔥",
        category: "STREAK",
        star_reward: 15,
        tier: "BRONZE",
        condition_type: "STREAK",
        condition_value: 3,
    },
    STREAK_7: {
        code: "STREAK_7",
        name: "Cam kết",
        description: "Điểm danh 7 ngày liên tiếp",
        icon: "💪",
        category: "STREAK",
        star_reward: 40,
        tier: "SILVER",
        condition_type: "STREAK",
        condition_value: 7,
    },
    STREAK_30: {
        code: "STREAK_30",
        name: "Tháng nóng",
        description: "Điểm danh 30 ngày liên tiếp",
        icon: "🔥",
        category: "STREAK",
        star_reward: 150,
        tier: "GOLD",
        condition_type: "STREAK",
        condition_value: 30,
    },
    STREAK_100: {
        code: "STREAK_100",
        name: "Siêu streak",
        description: "Điểm danh 100 ngày liên tiếp",
        icon: "🌟",
        category: "STREAK",
        star_reward: 500,
        tier: "DIAMOND",
        condition_type: "STREAK",
        condition_value: 100,
    },

    // RANK achievements
    RANK_SILVER: {
        code: "RANK_SILVER",
        name: "Vượt qua đồng",
        description: "Đạt rank Bạc (500 sao)",
        icon: "🥈",
        category: "RANK",
        star_reward: 50,
        tier: "SILVER",
        condition_type: "RANK",
        condition_value: 500,
    },
    RANK_GOLD: {
        code: "RANK_GOLD",
        name: "Vàng rực rỡ",
        description: "Đạt rank Vàng (2000 sao)",
        icon: "🥇",
        category: "RANK",
        star_reward: 100,
        tier: "GOLD",
        condition_type: "RANK",
        condition_value: 2000,
    },
    RANK_PLATINUM: {
        code: "RANK_PLATINUM",
        name: "Bạch kim",
        description: "Đạt rank Bạch Kim (5000 sao)",
        icon: "💎",
        category: "RANK",
        star_reward: 200,
        tier: "PLATINUM",
        condition_type: "RANK",
        condition_value: 5000,
    },
    RANK_DIAMOND: {
        code: "RANK_DIAMOND",
        name: "Kim cương",
        description: "Đạt rank Kim Cương (10000 sao)",
        icon: "💠",
        category: "RANK",
        star_reward: 500,
        tier: "DIAMOND",
        condition_type: "RANK",
        condition_value: 10000,
    },

    // TOTAL STARS
    STARS_1000: {
        code: "STARS_1000",
        name: "Nghìn sao",
        description: "Tích lũy 1000 sao",
        icon: "✨",
        category: "SPECIAL",
        star_reward: 50,
        tier: "SILVER",
        condition_type: "TOTAL_STARS",
        condition_value: 1000,
    },
    STARS_5000: {
        code: "STARS_5000",
        name: "Năm nghìn sao",
        description: "Tích lũy 5000 sao",
        icon: "🌈",
        category: "SPECIAL",
        star_reward: 150,
        tier: "GOLD",
        condition_type: "TOTAL_STARS",
        condition_value: 5000,
    },
    STARS_10000: {
        code: "STARS_10000",
        name: "Vạn sao",
        description: "Tích lũy 10000 sao",
        icon: "🌌",
        category: "SPECIAL",
        star_reward: 300,
        tier: "PLATINUM",
        condition_type: "TOTAL_STARS",
        condition_value: 10000,
    },
};

export const ACHIEVEMENT_CATEGORY_ORDER = [
    "STREAK",
    "SURVEY_CREATION",
    "PARTICIPATION",
    "SOCIAL",
    "SPECIAL",
    "RANK",
];