export const QUESTION_TYPES = Object.freeze({
  SINGLE_CHOICE: "SINGLE_CHOICE",
  DROPDOWN: "DROPDOWN",
  MULTIPLE_CHOICE: "MULTIPLE_CHOICE",
  RATING: "RATING",
  NUMBER: "NUMBER",
  DATE: "DATE",
  TEXT: "TEXT",
  PARAGRAPH: "PARAGRAPH",
  EMAIL: "EMAIL",
});

export const CHOICE_TYPES = Object.freeze([
  QUESTION_TYPES.SINGLE_CHOICE,
  QUESTION_TYPES.MULTIPLE_CHOICE,
  QUESTION_TYPES.DROPDOWN,
]);

